package net.dpco.pdf.enums.payment;

public enum PaymentStatus {
  START,
  BEFORE_GET_TOKEN,
  GET_TOKEN_SUCCEED,
  GET_TOKEN_FAILED,
  GET_TOKEN_EXCEPTION,
  BANK_GATEWAY_RESULT_EXPIRE_TOKEN,
  BANK_GATEWAY_RESULT_SUCCEED,
  BANK_GATEWAY_RESULT_FAILED,
  BEFORE_VERIFY_PAYMENT,
  BANK_VERIFY_PAYMENT_SUCCEED,
  BANK_VERIFY_PAYMENT_FAILED,
  BANK_VERIFY_PAYMENT_EXCEPTION,
  ;
}
